version: '3'
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  tomcat:
    image: tomcat:9
    ports:
      - "8888:8080"
    volumes:
      - ./target/my-maven-tom-1.0-SNAPSHOT.jar:/usr/local/tomcat/webapps/my-maven-tom-1.0-SNAPSHOT.jar
