version: '3'
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  tomcat:
    image: tomcat:9
    ports:
      - "8888:8080"
    volumes:
      - ./target/your-app.war:/usr/local/tomcat/webapps/your-app.war
